-   id: prettier
    name: prettier
    description: ''
    entry: prettier --write --ignore-unknown
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["prettier@3.5.1"]
    minimum_pre_commit_version: '0'
